In [ ]:
import numpy as np


In [ ]:
#10 нулей
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#10 единиц
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#10 пятерок
a=np.ones(10)*5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#Создать массив из целых чисел от 10 до 50
a=np.arange(10,51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
#Создать массив из четных чисел от 10 до 50
a=np.arange(10,51,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#Создать матрицу 3х3 с числами от 0 до 8
a=np.arange(0,9)
b=a.reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Создать единичную матрицу 3x3
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Используйте NumPy для генерации случайного числа от 0 до 1
a=np.random.rand()
print(a)

0.4107173541910857


In [ ]:
#Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
a=np.random.rand(25)
print(a)

[0.68910068 0.29910753 0.53321449 0.0593345  0.6419765  0.36308716
 0.77961043 0.93360956 0.40414869 0.22298352 0.94059917 0.42328895
 0.93898877 0.61002959 0.14946142 0.95920979 0.0240823  0.99933639
 0.86525377 0.56687106 0.10510709 0.69662273 0.79188348 0.80343005
 0.41026632]


In [ ]:
a=np.arange(0.01,1.01,0.01)
b=a.reshape(10,10)
print(b)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print('array',mat[2:,1:])

array [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
print(mat[3:4,4:])

[[20]]


In [ ]:
print('array',mat[0:3,1:2])

array [[ 2]
 [ 7]
 [12]]


In [ ]:
print('array',mat[4:])

array [[21 22 23 24 25]]


In [ ]:
print('array',mat[3:])

array [[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(mat.sum())

325


In [ ]:
print(mat.std())

7.211102550927978


In [ ]:
print(mat.sum(axis=0))

[55 60 65 70 75]
